---
duplication:
  enabled: true
  exclude_paths:
    - "examples/**"
metrics:
  enabled: true
  exclude_paths:
    - "examples/**"
coverage:
  enabled: true
  exclude_paths:
    - "examples/**"
exclude_paths:
  - examples/**
  - docs/**
