language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
git:
  depth: 3
branches:
  only:
  - master
  - develop    
  - /^greenkeeper/.*$/
after_success:
  - npm run coverage
  - npm run test-with-coverage  
deploy:
  provider: npm
  email: stw@linux.com
  api_key: $NPM_TOKEN
  on:
    branch: master