name: Compile and Test
on:
  push:
    branches:
      - main
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
          verbose: true
